iam-role      = "Jenkins-iam-role"
vpc-name      = "Jenkins-vpc"
igw-name      = "Jenkins-igw"
rt-name       = "Jenkins-rt"
sg-name       = "Jenkins-sg"
key-name      = "terraform-example"
instance-name = "Jenkins-Server"