iam-role      = "jenkins-iam-role"
vpc_name      = "jenkins-vpc"
igw-name      = "jenkins-igw"
rt-name       = "jenkins-rt"
sg-name       = "jenkins-sg"
key-name      = "DevSec"
instance-name = "Jenkins-Server"
subnet-name   = "jenkins-subnet"