cluster-name        = "Tetris-EKS-Cluster"
vpc_name            = "jenkins-vpc"
subnet-name         = "jenkins-subnet"
igw-name            = "jenkins-igw"
security-group-name = "jenkins-sg"
subnet-name2        = "jenkins-subnet2"
rt2-name            = "jenkins-rt2"
node-group-name    = "Tetris-EKS-Node-Group"